#!/usr/bin/env bash

readonly NAME_CONTAINER=vivaldi
readonly VERSION_VIVALDI=2.11
readonly OPTIONS_VIVALDI=( )

mkdir -p ~/.config/vivaldi ~/Downloads

if ! docker exec "${NAME_CONTAINER}" vivaldi "${OPTIONS_VIVALDI[@]}" "$@"; then
    xhost +local:docker
    docker run --rm --privileged --name="${NAME_CONTAINER}" \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v ~/Downloads:/home/vivaldi/Downloads \
        -v ~/.config/vivaldi:/home/vivaldi/.config/vivaldi \
        -v ~/.config/pulse/cookie:/home/vivaldi/.config/pulse/cookie:ro \
        -v /var/run/user/${UID}/pulse/native:/var/run/user/${UID}/pulse/native:ro \
        -v /etc/localtime:/etc/localtime:ro \
        -v /dev/shm:/dev/shm \
        -v /var/run/dbus:/var/run/dbus:ro \
        -v /dev/bus/usb:/dev/bus/usb \
        -v /dev/video0:/dev/video0 \
        -v /dev/video1:/dev/video1 \
        -v /dev/video2:/dev/video2 \
        -v /dev/video3:/dev/video3 \
        ${USER}/vivaldi:"${VERSION_VIVALDI}" "${OPTIONS_VIVALDI[@]}" "$@"
fi
